package APIFirstDemo;

public class MockJson {

	public static String SlotJSON()
	{
		return "{\r\n"
				+ "            \"AvailableSlots\": [\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 9:00:00 AM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 9:25:00 AM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 9:40:00 AM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 10:05:00 AM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 10:20:00 AM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 10:45:00 AM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 11:00:00 AM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 11:25:00 AM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 11:40:00 AM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 12:05:00 PM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 12:20:00 PM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 12:45:00 PM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 1:00:00 PM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 1:25:00 PM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 1:40:00 PM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 2:05:00 PM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 2:20:00 PM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 2:45:00 PM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 3:00:00 PM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 3:25:00 PM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 3:40:00 PM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 4:05:00 PM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"PropertyId\": 409082,\r\n"
				+ "                    \"dtStart\": \"1/18/2022 4:20:00 PM\",\r\n"
				+ "                    \"dtEnd\": \"1/18/2022 4:45:00 PM\",\r\n"
				+ "                    \"TypeofSlot\": \"GuidedTour\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        }" ;
				
				
	}
	
}
